# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNKFSZ0mED6Ujgby8YV1sNHNRv-5sXt9
"""

from time import sleep
print("joguin dos crias")
print("*música contagiante*")
sleep(5)




import random

numero = random.randint(1, 100)
print("Adivinhe o número aleatório:")
tentativa = 1
while tentativa <= 10:
 palpite = int(input("tente adivinhar o número: "))
 if tentativa == numero:
  print("PARABÉNS, VOCÊ ACERTOU!")
  break
 elif tentativa < numero:
  print("está frio, tente um número maior")
 else:
  print("quase lá, tente um número menor")
  tentativa +=1
if tentativa > 10:
   print("você não acertou, o número era:", numero)